apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  schedule: "0 0 * * *"
  startingDeadlineSeconds: 60
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: django-clearsessions
              image: gont1er/k8s-django-dev:d3132a7
              env:
                - name: DEBUG
                  value: "False"
                - name: ALLOWED_HOSTS
                  value: "*"
                - name: SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: django-secret
                      key: SECRET_KEY
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: django-secret
                      key: DATABASE_URL
              command: ["python", "manage.py", "clearsessions"]
